add lecture-2 home work
RomanShitovGH/react_project pull request #2
Opened 2023-11-19 13:42 UTC by RomanShitovGH

2023-11-20 16:50 UTC, SArchieEdu requested changes
нужны правки

2023-11-20 16:50 UTC, SArchieEdu commented on src/components/card/component.jsx
> +export const Card = ({ item }) => {
Нейминг очень общий. В карточке может быть все, что угодно. Лучше `Restaurant`

2023-11-20 16:50 UTC, SArchieEdu commented on src/components/cards/component.jsx
> +export const Cards = ({ restaurants }) => {
Restaurants

2023-11-20 16:50 UTC, SArchieEdu commented on src/components/dish/component.jsx
> +    <>
лишний

2023-11-20 16:50 UTC, SArchieEdu commented on src/components/dish/component.jsx
> +      <li>
тег li используется только в списке, используя его в дочернем элементе вы ограничиваете его область использования. Лучше дочерний элемент просто обернуть в него в месте использования, но не тащить в сам компонент. на лекции еще более подробно расскажу про это

2023-11-20 16:50 UTC, SArchieEdu commented on src/components/dishes/component.jsx
> +    <>
лишний

2023-11-20 16:50 UTC, SArchieEdu commented on src/components/dishes/component.jsx
> +          <Dish item={item} />
для блюда это не айтем, а блюдо

2023-11-20 16:50 UTC, SArchieEdu commented on src/components/name-item/component.jsx
> +export const NameItem = ({ item }) => {
Нейминг очень непонятный - имяЭлемент

2023-11-20 16:50 UTC, SArchieEdu commented on src/components/names-list/component.jsx
> +export const NamesList = ({ reastaurantNames }) => {
Нейминг очень непонятный - лист имен

2023-11-20 16:50 UTC, SArchieEdu commented on src/components/review/component.jsx
> +    <>
лишний

2023-11-20 16:50 UTC, SArchieEdu commented on src/components/review/component.jsx
> +      <li>
тег li используется только в списке, используя его в дочернем элементе вы ограничиваете его область использования. Лучше дочерний элемент просто обернуть в него в месте использования, но не тащить в сам компонент. на лекции еще более подробно расскажу про это

2023-11-20 16:50 UTC, SArchieEdu commented on src/components/reviews/component.jsx
> +    <>
лишний

2023-11-20 17:14 UTC, RomanShitovGH commented on src/components/cards/component.jsx
> +export const Cards = ({ restaurants }) => {
Не совсем понял, это нужно переменную пропсов с большой буквы что ли?

2023-11-23 11:03 UTC, SArchieEdu approved these changes

2023-11-23 11:57 UTC, merged